# Generated by Django 3.1 on 2021-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Región')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Sector')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TamanoEmpresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Tamaño de empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tamaño de empresa',
                'verbose_name_plural': 'Tamaños de empresa',
                'db_table': 'tamano_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCapital',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, verbose_name='Tipo de capital')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de capital',
                'verbose_name_plural': 'Tipos de capital',
                'db_table': 'tipocapitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Tipo de empresa')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de empresa',
                'verbose_name_plural': 'Tipos de empresa',
                'db_table': 'tipo_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Zona')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zonas',
                'ordering': ['region', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=12, verbose_name='Nº de Cédula')),
                ('rif', models.CharField(max_length=10, verbose_name='RIF')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono(s)')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Ramo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramos',
                'db_table': 'ramos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['nombre', 'pais'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.estado', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ramo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.ramo', verbose_name='Ramo')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['nombre'],
            },
        ),
    ]
