# Generated by Django 3.1 on 2021-06-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('porcentaje', models.IntegerField(unique=True, verbose_name='Porcentaje')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'etapas',
                'ordering': ['porcentaje', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoGestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de gestión',
                'verbose_name_plural': 'Tipos de gestión',
                'db_table': 'tipogestiones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoOportunidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de oportunidad',
                'verbose_name_plural': 'Tipos de oportunidad',
                'db_table': 'tipooportunidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(auto_now=True, verbose_name='Fecha de inicio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cerrada', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('etapas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdv.etapa', verbose_name='Etapa')),
                ('terceros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero', verbose_name='Tercero')),
                ('tipooportunidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdv.tipooportunidad', verbose_name='Tipo de oportunidad')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'db_table': 'oportunidades',
                'ordering': ['terceros', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resultados', models.TextField(blank=True, verbose_name='Resultados')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('terceros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero', verbose_name='Tercero')),
                ('tipogestiones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdv.tipogestion', verbose_name='Tipo de gestión')),
            ],
            options={
                'verbose_name': 'Gestion',
                'verbose_name_plural': 'Gestiones',
                'db_table': 'gestiones',
                'ordering': ['fecha', 'terceros', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_instalada', models.TextField(verbose_name='Base instalada')),
                ('erps', models.TextField(verbose_name='ERP/Sistema')),
                ('dbms', models.TextField(verbose_name='Manejador(es) de base de datos')),
                ('osystems', models.TextField(verbose_name='Sistemas operativos')),
                ('num_usuarios', models.IntegerField(verbose_name='Número de usuarios')),
                ('notas', models.TextField(verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('terceros', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'db_table': 'fichas',
                'ordering': ['terceros'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de documento')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envío')),
                ('tipo_documento', models.CharField(choices=[('PRESENTACION', 'Presentacion'), ('COTIZACIÓN', 'Cotizacion'), ('PROPUESTA', 'Propuesta'), ('CONTRATO', 'Contrato'), ('BROCHURE', 'Brochure'), ('CUESTIONARIO', 'Cuestionario')], default='COTIZACIÓN', max_length=20, verbose_name='Tipo de documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/% Y/% m/% d/', verbose_name='Archivo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('oportunidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fdv.oportunidad', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['fecha', 'fecha_envio', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Captacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=80, verbose_name='Nombre empresa')),
                ('nombre_persona', models.CharField(blank=True, max_length=60, verbose_name='Nombre persona')),
                ('telefono_persona', models.CharField(blank=True, max_length=50, verbose_name='Teléfonos')),
                ('telefono_empresa', models.CharField(blank=True, max_length=50, verbose_name='Teléfonos')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=250, verbose_name='Email')),
                ('tipo_oportunidad', models.TextField(verbose_name='Tipo de oportunidad')),
                ('gestion', models.TextField(blank=True, verbose_name='Gestión')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Captación',
                'verbose_name_plural': 'Captaciones',
                'db_table': 'captaciones',
                'ordering': ['nombre_empresa', 'nombre_persona'],
            },
        ),
    ]
